# Generated by Django 3.2.16 on 2022-11-16 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '名簿',
                'verbose_name_plural': '名簿',
            },
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_at', models.DateField(default=django.utils.timezone.now, verbose_name='活動日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='登録日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nakanojo.member', verbose_name='お名前')),
            ],
            options={
                'verbose_name': '活動記録',
                'verbose_name_plural': '活動記録',
            },
        ),
    ]
