# Generated by Django 3.2.16 on 2023-04-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.PositiveIntegerField(default=0, verbose_name='トークン数')),
                ('character', models.PositiveIntegerField(default=0, verbose_name='文字数')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'ChatGPT',
                'verbose_name_plural': 'ChatGPT',
            },
        ),
    ]
