# Generated by Django 4.2.11 on 2024-03-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGPT',
        ),
    ]
